config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  resources :games do
    resource :points, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :opponent, class_name: 'User'

  validates :user_id, presence: true
  validates :opponent_id, presence: true

  has_many :points
  
end

app/models/kind.rb
class Kind < ApplicationRecord
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :game
  belongs_to :server, class_name: 'User'
  belongs_to :point_user, class_name: 'User'
  belongs_to :kind
  belongs_to :service
  
  validates :game_id, presence: true
  validates :server_id, presence: true
  validates :point_user_id, presence: true
  validates :kind_id, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :games
  has_many :opponents, class_name: 'Game', foreign_key: 'follow_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  include UsersHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    @point = Point.new
  end

  def new
    @game = current_user.games.build
    unless params[:opponent]
      # oppnentが未設定の時はゲストユーザーを設定
      @guest = User.find(1)
      @game.opponent_id = @guest.id
    end
    @game.save
    redirect_to controller: :games, action: :show, id: @game.id
    
  end

  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:success] = 'ゲームを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def game_params
    params.require(:game).permit(:oppnent)
  end
  
  def calcScore
    
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @point = @game.points.build(point_params)
    @point.save
    @points = @game.points
    render template: "games/show"
  end
  
  def destroy
    
  end
  
  private
  
  def point_params
    params.require(:point).permit(:game_id, :server_id, :point_user_id, :kind_id, :service_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @game = current_user.games.build
      @games = current_user.games.order('created_at desc').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def calcPoint
    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_user_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.name
  end
end

app/views/games/_games.html.erb
<table class="table table-hover">
  <%= link_to 'New Game', new_game_path, class: "btn btn-success" %>
  <thead>
    <tr>
      <th>Date</th>
      <th>Opponent</th>
      <th>Score</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% games.each do |game| %>
    <tr>
      <td><%= game.created_at %></td>
      <td><%= show_user_name(game.opponent_id) %></td>
      <td class="score"></td>
      <td><%= link_to 'Show Game', game_path(game), class: "btn btn-primary" %></td>
      <td><%= link_to 'Delete', game_path(game), method: :delete, data: {confirm: "You sure?"}, class: 'btn btn-danger' %>
</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/games/_score-board.html.erb
<!--<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<title>Score Board</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="css/main.css" type="text/css" />
</head>
<body>
	<!--<nav class="navbar navbar-default" style="">
	  <div class="container-fluid bg-info">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Score Board</a>
	    </div>
	
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="#">setting<span class="sr-only">(current)</span></a></li>
	      </ul>
	    </div>
	  </div>
	</nav>-->
	<div class="score-board">
		<div ="status-wrapper">
			<div class="match-status">
				<div class="player-info col-xs-3">
					<div class="player-name player1">Player1</div>
					<div class="player-name player2">Player2</div>
				</div>
				<div class="server-info col-xs-1">
					<span class="glyphicon glyphicon-arrow-left unvisible"></span>
					<span class="glyphicon glyphicon-arrow-left unvisible"></span>
				</div>
				<div class="winner-info col-xs-1">
					<span class="glyphicon glyphicon-ok unvisible"></span>
					<span class="glyphicon glyphicon-ok unvisible"></span>
				</div>
				<div class="result result-wrapper col-xs-7">
					<div class="pts col-xs-2">
						<div class="pts-1">0</div>
						<div class="pts-info">PTS</div>
						<div class="pts-2">0</div>
					</div>
					<div class="set set1 col-xs-2">
						<span class="score">0<span class="tiebreak"></span></span>
						<div class="set-info">1</div>
						<span class="score">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set2 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">2</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set3 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">3</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set4 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">4</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set5 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">5</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
				</div>
			</div>
		</div>
		<div class="input-point">
			<div class="point-wrapper">
				<button type="button" class="btn btn-warning fault-button">
					<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
					FAULT
				</button>
			</div>
			<div class="button-wrapper player1-button">
				<div class="btn-group">
				  <button type="button" class="btn btn-primary dropdown-toggle winner-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    WINNER<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu">
				    <li class="ace-button"><a href="#">SERVICE ACE</a></li>
				    <li class="netpoint-button"><a href="#">NET POINT</a></li>
				    <li class="otherpoint-button"><a href="#">OTHER</a></li>
				  </ul>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-danger dropdown-toggle error-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    EORROR<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu">
				    <li class="unferror-button"><a href="#">UNFORCED</a></li>
				    <li class="ferror-button"><a href="#">FORCED</a></li>
				    <li class="doublefault-button"><a href="#">DOUBLE FAULT</a></li>
				  </ul>
				</div>
			</div>
			<div class="button-wrapper player2-button">
				<div class="btn-group">
				  <button type="button" class="btn btn-primary dropdown-toggle winner-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    WINNER<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu">
				    <li class="ace-button"><a href="#">SERVICE ACE</a></li>
				    <li class="netpoint-button"><a href="#">NET POINT</a></li>
				    <li class="otherpoint-button"><a href="#">OTHER</a></li>
				  </ul>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-danger dropdown-toggle error-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    EORROR<span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu dropdown-menu-right">
				    <li class="unferror-button"><a href="#">UNFORCED</a></li>
				    <li class="ferror-button"><a href="#">FORCED</a></li>
				    <li class="doublefault-button"><a href="#">DOUBLE FAULT</a></li>
				  </ul>
				</div>
			</div>
		<div class="stats-wrraper">
			<div class="stats-player-name">
				<div class="stats-player-name1">Player1</div>
				<div class="stats-player-name2">Player2</div>
			</div>
			<div class="stats">
				<div class="stats-detail">
					<div class="aces1 stats-player1"></div>
					<div class="stats-info">ACES</div>
					<div class="aces2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="doubleFault1 stats-player1"></div>
					<div class="stats-info">DOUBLE FAULTS</div>
					<div class="doubleFault2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="firstServeIn1 stats-player1"></div>
					<div class="stats-info">FIRST SERVE IN</div>
					<div class="firstServeIn2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winOn1stServe1 stats-player1"></div>
					<div class="stats-info">WIN ON 1ST SERVE</div>
					<div class="winOn1stServe2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winOn2ndServe1 stats-player1"></div>
					<div class="stats-info">WIN ON 2ND SERVE</div>
					<div class="winOn2ndServe2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="netPointWon1 stats-player1"></div>
					<div class="stats-info">NET POINTS WON</div>
					<div class="netPointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="breakPointWon1 stats-player1"></div>
					<div class="stats-info">BREAK POINTS WON</div>
					<div class="breakPointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="receivePointWon1 stats-player1"></div>
					<div class="stats-info">RECEIVING POINTS WON</div>
					<div class="receivePointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winner1 stats-player1"></div>
					<div class="stats-info">WINNER</div>
					<div class="winner2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="unfError1 stats-player1"></div>
					<div class="stats-info">UNFORCED ERRORS</div>
					<div class="unfError2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="totalPoint1 stats-player1"></div>
					<div class="stats-info">TOTAL POINTS WON</div>
					<div class="totalPoint2 stats-player2"></div>
				</div>
			</div>
		</div>
	</div>
	<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="js/main.js"></script>
</body>
</html>-->

app/views/games/new.html.erb
<%= render 'games/score-board' %>

app/views/games/show.html.erb
<div class="wrapper">
  <div class="score-board">
	<%= form_for(@point, url: game_points_path(@game), html: {method: "post"}) do |f| %>
	  <%= f.hidden_field :user_id, :value => @game.user_id %>
	  <%= f.hidden_field :opponent_id, :value => @game.opponent_id %>
	  <%= f.hidden_field :server_id %>
	  <%= f.hidden_field :kind_id %>
	  <%= f.hidden_field :point_user_id %>
	  <%= f.hidden_field :service_id %>
		<div class="status-wrapper">
			<div class="match-status">
				<div class="player-info col-xs-3">
					<div class="player-name player1"><%= show_user_name(@game.user_id) %></div>
					<div class="player-name player2"><%= show_user_name(@game.opponent_id) %></div>
				</div>
				<div class="server-info col-xs-1">
					<span class="glyphicon glyphicon-arrow-left unvisible"></span>
					<span class="glyphicon glyphicon-arrow-left unvisible"></span>
				</div>
				<div class="winner-info col-xs-1">
					<span class="glyphicon glyphicon-ok unvisible"></span>
					<span class="glyphicon glyphicon-ok unvisible"></span>
				</div>
				<div class="result result-wrapper col-xs-7">
					<div class="pts col-xs-2">
						<div class="pts-1">0</div>
						<div class="pts-info">PTS</div>
						<div class="pts-2">0</div>
					</div>
					<div class="set set1 col-xs-2">
						<span class="score">0<span class="tiebreak"></span></span>
						<div class="set-info">1</div>
						<span class="score">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set2 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">2</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set3 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">3</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set4 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">4</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
					<div class="set set5 col-xs-2">
						<span class="score unvisible">0<span class="tiebreak"></span></span>
						<div class="set-info">5</div>
						<span class="score unvisible">0<span class="tiebreak"></span></span>
					</div>
				</div>
			</div>
		</div>
		<div class="input-point">
			<div class="button-wrapper">
				<!-- Button trigger modal -->
				<button type="button" class="btn btn-primary player1-button" data-toggle="modal" data-target="#myModal">
					<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
					<%= show_user_name(@game.user_id) %>
				</button>
				<button type="button" class="btn btn-warning player2-button" data-toggle="modal" data-target="#myModal">
					<span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
					<%= show_user_name(@game.opponent_id) %>
				</button>
				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog modal-lg" role="document">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Point Detail</h4>
				      </div>
				      <div class="modal-body point-detail">
								<form class="form">
								  <div class="form-group">
										<label class="radio">
										  <input type="radio" name="KindOptions" id="ace" value="1">
										  <span class="text-primary">SERVICE ACE</span>
										</label>
										<label class="radio">
										  <input type="radio" name="KindOptions" id="net-point" value="2">
										  <span class="text-primary">NET POINT</span>
										</label>
										<label class="radio">
										  <input type="radio" name="KindOptions" id="other-point" value="3">
										  <span class="text-primary">OTHER POINT</span>
										</label>
										<label class="radio">               
										  <input type="radio" name="KindOptions" id="unf-error" value="4">
										  <span class="text-danger">UNFORCED ERROR</span>
										</label>
										<label class="radio">
										  <input type="radio" name="KindOptions" id="forced-error" value="5">
										  <span class="text-danger">FORCED ERROR</span>
										</label>
										<label class="radio">
										  <input type="radio" name="KindOptions" id="double-fault" value="6">
										  <span class="text-danger">DOUBLE FAULT</span>
										</label>
								  </div>
								</form>
								<form class="form">
								  <div class="form-group">
									<label class="radio">
									  <input type="radio" name="ServiceOptions" id="first-service-in" value="1">
									  <span class="text-primary">1st Service In</span>
									</label>
									<label class="radio">
									  <input type="radio" name="ServiceOptions" id="second-service-in" value="2">
									  <span class="text-warning">2nd Service In</span>
									</label>
								  </div>
								</form>
				      </div>
				      <div class="modal-footer">
						<%= f.submit 'Submit', class: 'btn btn-success btn-block point-submit' %>
				      </div>
				    </div>
				  </div>
				</div>
			</div>
		<div class="stats-wrraper">
			<!--<div class="stats-player-name">
				<div class="stats-player-name1"><%= show_user_name(@game.user_id) %></div>
				<div class="stats-player-name2"><%= show_user_name(@game.opponent_id) %></div>
			</div>-->
			<div class="stats">
				<div class="stats-detail">
					<div class="aces1 stats-player1"></div>
					<div class="stats-info">ACES</div>
					<div class="aces2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="doubleFault1 stats-player1"></div>
					<div class="stats-info">DOUBLE FAULTS</div>
					<div class="doubleFault2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="firstServeIn1 stats-player1"></div>
					<div class="stats-info">FIRST SERVE IN</div>
					<div class="firstServeIn2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winOn1stServe1 stats-player1"></div>
					<div class="stats-info">WIN ON 1ST SERVE</div>
					<div class="winOn1stServe2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winOn2ndServe1 stats-player1"></div>
					<div class="stats-info">WIN ON 2ND SERVE</div>
					<div class="winOn2ndServe2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="netPointWon1 stats-player1"></div>
					<div class="stats-info">NET POINTS WON</div>
					<div class="netPointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="breakPointWon1 stats-player1"></div>
					<div class="stats-info">BREAK POINTS WON</div>
					<div class="breakPointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="receivePointWon1 stats-player1"></div>
					<div class="stats-info">RECEIVING POINTS WON</div>
					<div class="receivePointWon2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="winner1 stats-player1"></div>
					<div class="stats-info">WINNER</div>
					<div class="winner2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="unfError1 stats-player1"></div>
					<div class="stats-info">UNFORCED ERRORS</div>
					<div class="unfError2 stats-player2"></div>
				</div>
				<div class="stats-detail">
					<div class="totalPoint1 stats-player1"></div>
					<div class="stats-info">TOTAL POINTS WON</div>
					<div class="totalPoint2 stats-player2"></div>
				</div>
			</div>
		</div>
	<% end %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tennis Score Board</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Scoreboard</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>user name：<%= current_user.name %></p>
  <%= render 'games/games', games: @games %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Tennis Score Board</h1>
      <%= link_to 'Sign up', signup_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form_group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form_group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form_group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form_group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
      
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>